import IconInfo from 'assets/svg/info.svg'
import IconCheck from 'assets/svg/check.svg'
import IconDanger from 'assets/svg/danger.svg'
import IconBell from 'assets/svg/bell.svg'
import IconClose from 'assets/svg/close.svg'
import IconLock from 'assets/svg/lock.svg'
import IconProfile from 'assets/svg/profile.svg'
import IconImage from 'assets/svg/image.svg'
import IconHeart from 'assets/svg/heart.svg'
import IconMathPlus from 'assets/svg/math-plus.svg'
import IconNotes from 'assets/svg/notes.svg'
import IconUser from 'assets/svg/user.svg'
import IconDetailsMore from 'assets/svg/details-more.svg'

export { IconInfo, IconCheck, IconDanger, IconBell, IconClose, IconLock, IconProfile, IconImage, IconHeart, IconMathPlus, IconNotes, IconUser, IconDetailsMore }
