import IconInfo from 'Assets/svg/info.svg'
import IconCheck from 'Assets/svg/check.svg'
import IconDanger from 'Assets/svg/danger.svg'
import IconBell from 'Assets/svg/bell.svg'
import IconClose from 'Assets/svg/close.svg'
import IconLock from 'Assets/svg/lock.svg'
import IconProfile from 'Assets/svg/profile.svg'
import IconImage from 'Assets/svg/image.svg'
import IconHeart from 'Assets/svg/heart.svg'
import IconMathPlus from 'Assets/svg/math-plus.svg'
import IconNotes from 'Assets/svg/notes.svg'
import IconUser from 'Assets/svg/user.svg'
import IconDetailsMore from 'Assets/svg/details-more.svg'

export { IconInfo, IconCheck, IconDanger, IconBell, IconClose, IconLock, IconProfile, IconImage, IconHeart, IconMathPlus, IconNotes, IconUser, IconDetailsMore }
