name: Build
on:
  push:
    branches:
      - main
      - stable
  pull_request_target:
    branches:
      - main
      - stable
env:
  IMAGE_NAME: fun-tour
  PORT_PROD: 8091
  PORT_STABLE: 8092
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.1.1
        with:
          node-version: 16
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7
          run_install: false
      - run: |
          pnpm install
          pnpm build
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ./dist
