name: Deploy
on:
  workflow_run:
    workflows:
      - Build
    types:
      - completed
env:
  IMAGE_NAME: fun-tour
  PORT_PROD: 8091
  PORT_STABLE: 8092
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - if: github.ref_name == 'main' || github.base_ref == 'main'
        run: |
          echo "PRO_PROT=$PORT_PROD" >> $GITHUB_ENV
          echo "PRO_ENV=prod" >> $GITHUB_ENV
      - uses: appleboy/ssh-action@master
        env:
          DOCKER_CONTAINER: ${{ secrets.DOCKERHUB_USERNAME }}_${{ env.IMAGE_NAME }}_${{ env.PRO_ENV }}
          DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}_${{ env.PRO_ENV }}
        with:
          host: ${{ secrets.REMOTE_HOST }}
          key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          username: ${{ secrets.REMOTE_USERNAME }}
          script: |
            docker rm -f ${{ env.DOCKER_CONTAINER }}
            docker rmi -f ${{ env.DOCKER_IMAGE }}
            docker pull ${{ env.DOCKER_IMAGE }}
            docker run --name ${{ env.DOCKER_CONTAINER }} -p ${{ env.PRO_PORT }}:80 -dit ${{ env.DOCKER_IMAGE }}
