name: Push
on:
  workflow_run:
    workflows: ['Build']
    types:
      - completed
env:
  IMAGE_NAME: fun-tour
  PORT_PROD: 8091
  PORT_STABLE: 8092
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - if: github.ref_name == 'main' || github.base_ref == 'main'
        run: echo "PRO_ENV=prod" >> $GITHUB_ENV
      - if: github.ref_name == 'stable' || github.base_ref == 'stable'
        run: echo "PRO_ENV=stable" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: success
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        env:
          DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}_${{ env.PRO_ENV }}
        with:
          context: .
          file: config/Dockerfile
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:${{ github.sha }},${{ env.DOCKER_IMAGE }}:latest
